# Generated by Django 2.2.13 on 2021-01-10 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='vk_token',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
